Allow tactical eager loading in combination with class table inheritance
jeremyevans/sequel pull request #1962
Opened 2022-11-13 11:38 UTC by rolftimmermans

Class table inheritance doesn't work in combination with tactical eager loading. There are no errors, but eager loading just isn't happening. I know this is intentional, but it makes it very difficult to manage performance when rendering a list of objects that use CTI if they make use of any association of the child classes.

This is a draft fix which seems to work nicely with our application. I'm opening this pull request to get your opinion. Is this on the right track? If so we'd be happy to polish and/or add more test cases.

The idea is that the `eager_load` method uses a concrete subclass rather than the parent model when performing eager loading. The tactical eager loading plugin takes care of passing in only the objects that are instances of the model on which the association was first used. This would always be the model that accesses this association.

I guess in theory it could still lead to some mild inefficiencies with very large hierarchies of inheritance. But that seems better than the status quo.

2022-11-13 17:47 UTC, jeremyevans requested changes
Thanks for working on this.  I like this approach, it doesn't require `tactical_eager_loading` knowing anything about `class_table_inheritance`.  There is extra code when doing a tactical eager load that is unnecessary if `class_table_inheritance` is not used, but I can handle that post-merging.

Please see one inline comment.

2022-11-13 17:47 UTC, jeremyevans commented on lib/sequel/model/associations.rb
> +        def eager_load(a, m=model, eager_assoc=@opts[:eager])
When adding an optional argument to an existing method, the optional argument should always be added at the end.

2022-11-13 19:38 UTC, rolftimmermans commented
Great, thanks! The argument order has been swapped.

2022-11-13 19:40 UTC, jeremyevans commented
Thanks!  I'll try to get this merged tomorrow.

2022-11-15 00:15 UTC, jeremyevans commented
Squash merged as 23189e9ff3d382781a5ed18194266d5be1fec1cd

2022-11-15 00:15 UTC, closed without merging

2022-11-15 22:54 UTC, jeremyevans commented
@rolftimmermans I made some changes to this support in 9a9f1119dfda85b10270763e5b0801b01cd401a7, can you review and let me know if that works for you?