Added run_sungle method to run single migration by version and direction
jeremyevans/sequel pull request #2093
Opened 2023-11-09 16:12 UTC by opya

The new method was added only for TimestampMigrator because I'm not sure that this is the correct way to do it.

Reference: https://github.com/jeremyevans/sequel/discussions/2045

2023-11-09 16:55 UTC, jeremyevans requested changes
I think the API should be different:

```ruby
  Sequel::TimestampMigrator.run_single(DB, '/path/to/filename', opts)
```

With this definition:

```ruby
  def TimestampMigrator.run_single(db, path, opts=OPTS)
    new(db, File.dirname(path), opts).run_single(path, opts[:direction])
  end
```

This avoids a lot of the unnecessary code in this pull request.  It also handles the case of multiple migrations with the same version (allowed by the TimestampMigrator). Can you switch to that approach?

2023-11-09 18:08 UTC, opya commented
sorry for the multiple commits, i think that the requested comments were addressed, sorry if forgot something

2023-11-09 19:51 UTC, jeremyevans requested changes
Looking better.  Please see some additional requested changes.

2023-11-09 19:51 UTC, jeremyevans commented on lib/sequel/extensions/migration.rb
> +    def run_single(path, direction)
This code should be removed.

2023-11-11 00:16 UTC, jeremyevans reviewed
This looks good.  I'll try to merge and test on Monday.

2023-11-13 16:40 UTC, opya commented
ok, thank you

2023-11-13 17:51 UTC, jeremyevans commented
Squash merged at 422f16040a09e5bf5f6298121f5e246f91418ea4

2023-11-13 17:51 UTC, closed without merging