Cache regexp objects in the sqlite adapter to improve performance
jeremyevans/sequel pull request #2108
Opened 2023-12-22 23:28 UTC by paddor

Nothing much, just what the title says. Theoretically, if an infinite amount of different regexp are used in SQL queries, it could of course fill up RAM, but I think that's uncommon.

In my case, this brought the runtime from ~300ms down to ~70ms for a query that uses one single regexp in a table with around ~5700 rows.

2023-12-23 07:29 UTC, jeremyevans requested changes
I'm OK with supporting this, but it must be conditional and off by default for backwards compatibility.  This introduces a potential memory leak for code that does not expect the regexps to be cached.

2023-12-23 18:44 UTC, paddor commented
I've changed the implementation. It now only caches Regexp objects if `setup_regexp_function => :cached` was given.

2023-12-23 21:01 UTC, paddor commented
Thinking about it a little longer, maybe the option `setup_regexp_function` should just support taking a block.

2023-12-23 22:40 UTC, paddor commented
This is how I plan to use it now:

```ruby
regexp_cache = Hash.new { |h, k| h[k] = Regexp.new(k, timeout: 0.005) }
opts = {
  setup_regexp_function: proc { |re_str, str| regexp_cache[re_str].match? str }
}
Sequel.connect('sqlite:///path/db.sqlite3', opts)
```

Let me know what you think. I left the `:cached` functionality in, with appropriate changes to the documentation. Let me know if I should remove it.

2023-12-27 18:18 UTC, jeremyevans commented
Squash merged at c8248241ddf1a8d5d06f296aab5dca40b777c7b8

2023-12-27 18:18 UTC, closed without merging

2023-12-27 22:57 UTC, paddor commented
Thanks!