MySQL and Postgres schema: retrieve columns' comments
jeremyevans/sequel pull request #2249
Opened 2024-11-10 00:18 UTC by Bahanix

Following this discussion:
- https://github.com/jeremyevans/sequel/discussions/2248

Here is a PR to retrieve columns' comments (+ collation + privileges for MySQL).

As @jeremyevans shared, it may be more appropriate to build an extension, similar to @mpalmer's https://github.com/mpalmer/sequel-pg-comment. No hard feeling if the PR is rejected, I mostly pushed it because it fixes my use case, and it could help people who would come across the same issue.

Thank you for your help finding this solution!

2024-11-10 00:32 UTC, jeremyevans requested changes
I'm still on the fence about accepting this.  But one of the prerequisites would be that specs are added to test for expected behavior.

2024-11-10 00:32 UTC, jeremyevans commented on doc/reflection.rdoc
> +:comment:: The comment of the column.
This should be clear that it is MySQL/PostgreSQL only.

2024-11-10 00:32 UTC, jeremyevans commented on lib/sequel/adapters/shared/mysql.rb
> +          row[:collation] = row.delete(:Collation)
Collation should not be included, nor privileges.  This PR is only for comment support.

2024-11-11 03:29 UTC, mpalmer commented
You'll definitely get shoved down the slippery slope.  It seems somewhat inconsistent to provide in-core support for just reading *some* kinds of comments on *some* database engines, while needing an extension to get more comprehensive support.  A `mysql_comment` plugin would seem to be the more consistent approach, to provide access to whatever support MySQL has for such things.

2024-11-11 11:45 UTC, Bahanix commented
> Using nil instead of the empty string seems like the best choice.

Change pushed

To give you some context about the need, Sequel is a dependency of Langchainrb which is a dependency of a project I work on. The more info Langchainrb can retrieve from the DB, the better the underlying AI can perform – this is why reading is enough here.

2024-11-11 20:15 UTC, jeremyevans commented
> You'll definitely get shoved down the slippery slope. It seems somewhat inconsistent to provide in-core support for just reading _some_ kinds of comments on _some_ database engines, while needing an extension to get more comprehensive support. A `mysql_comment` plugin would seem to be the more consistent approach, to provide access to whatever support MySQL has for such things.

I agree that it seems somewhat inconsistent.  However, if this handles the needs of 80% of users who would like some comment support, considering the limited invasiveness, I think it should be worth it.  I would be open to expanding the same type of support by default on other databases, as long as it was of similar invasiveness, so the slippery slope there doesn't bother me too much.  In terms of reading other types of comments, and writing comments, that would be a bigger issue, but maybe it isn't a problem to consider that.

2024-11-11 20:22 UTC, jeremyevans commented
> > Using nil instead of the empty string seems like the best choice.
> 
> Change pushed

Looks like you need to update the MySQL adapter spec you added for the change.

2024-11-11 21:01 UTC, Bahanix commented
Woopsy, fixed

2024-11-12 00:36 UTC, jeremyevans commented
Squash merged at b59c0aaac2511b56f35d69ffc43bb99200a3f2d1

2024-11-12 00:36 UTC, closed without merging